---
- name: Chrome - Add apt key
  shell: wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  when: ansible_distribution == 'Ubuntu'

- name: Chrome - Install repo
  become: yes
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Chrome - Add GPG key
  become: yes
  ansible.builtin.rpm_key:
    key: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  when: ansible_distribution == 'CentOS'

- name: Chrome - Add yum repository
  become: yes
  ansible.builtin.copy:
    content: |
      [google-chrome]
      name=google-chrome
      baseurl=http://dl.google.com/linux/chrome/rpm/stable/$basearch
      enabled=1
      gpgcheck=1
      gpgkey=https://dl.google.com/linux/linux_signing_key.pub
    dest: /etc/yum.repos.d/google-chrome.repo
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution == 'CentOS'

- name: Chrome - Install
  apt:
    name: google-chrome-stable
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Chrome - Install
  become: yes
  ansible.builtin.yum:
    name: google-chrome-stable
    state: present
  when: ansible_distribution == 'CentOS'
