---
#- include_tasks: awscli.yml
- include_tasks: chrome.yml
- include_tasks: docker.yml
- include_tasks: skype.yml
- include_tasks: spotify.yml
- include_tasks: terraform.yml
- include_tasks: zsh.yml