---
- name: Define PyCharm Community version and download URL
  set_fact:
    pycharm_version: "2023.1"
    pycharm_download_url: "https://download.jetbrains.com/python/pycharm-community-{{ pycharm_version }}.tar.gz"
    pycharm_install_dir: "/opt/pycharm-community"
    pycharm_executable_path: "/usr/local/bin/pycharm-community"

- name: Download PyCharm Community
  get_url:
    url: "{{ pycharm_download_url }}"
    dest: "/tmp/pycharm-community-{{ pycharm_version }}.tar.gz"
    mode: "u=rw,g=r,o=r"

- name: Create PyCharm Community installation directory
  file:
    path: "{{ pycharm_install_dir }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Unarchive PyCharm Community
  unarchive:
    src: "/tmp/pycharm-community-{{ pycharm_version }}.tar.gz"
    dest: "{{ pycharm_install_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Create PyCharm Community symbolic link
  file:
    src: "{{ pycharm_install_dir }}/bin/pycharm.sh"
    dest: "{{ pycharm_executable_path }}"
    state: link
    mode: "u=rwx,g=rx,o=rx"

# Optional: If you have custom configuration settings to apply
- name: Copy PyCharm Community configuration settings
  copy:
    src: "/path/to/your/custom/settings.zip"
    dest: "{{ ansible_env.HOME }}/.config/JetBrains/PyCharmCE{{ pycharm_version }}/settings.zip"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "u=rw,g=r,o=r"
