---
- name: Spotify - Add apt key.
  shell: curl -sS https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/repository-spotify-com-keyring.gpg


- name: Spotify - Install repo.
  become: yes
  apt_repository:
    repo: deb {{ spotify_repository_url }} {{ spotify_repository_channel }}
    filename: spotify
    state: present
    update_cache: yes

- name: Spotify - Install.
  apt:
    name: "{{ spotify_package_name }}"
    state: present