---
- name: Spotify - Download apt key.
  get_url:
    url: "{{ spotify_apt_key_url }}"
    dest: /tmp/spotify.gpg
    
- name: Spotify - Add apt key.
  ansible.builtin.apt_key:
    data: "{{ lookup('file', '/tmp/spotify.gpg') }}"
    state: present



- name: Spotify - Install repo.
  become: yes
  apt_repository:
    repo: deb {{ spotify_repository_url }} {{ spotify_repository_channel }}
    filename: spotify
    state: present
    update_cache: yes

- name: Spotify - Install.
  apt:
    name: "{{ spotify_package_name }}"
    state: present