- name: Spotify - Add apt key.
  copy:
    src: "{{ playbook_dir }}/files/spotify.gpg"
    dest: /etc/apt/trusted.gpg.d/spotify.gpg
    owner: root
    group: root
    mode: 0775

- name: Spotify - Install repo.
  become: yes
  apt_repository:
    repo: deb {{ spotify_repository_url }} {{ spotify_repository_channel }}
    filename: spotify
    state: present
    update_cache: yes

- name: Spotify - Install.
  apt:
    name: "{{ spotify_package_name }}"
    state: present
