---
- name: Spotify - Add apt key.
  shell: curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | sudo apt-key add -

- name: Spotify - Install repo.
  become: yes
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    filename: spotify
    state: present
    update_cache: yes

- name: Spotify - Install.
  apt:
    name: spotify-client
    state: present